### ISSUE TITLE
Unable to resolve dependency when installing with npm

### ISSUE THREAD

**Issue by kwam1na** [anatoliygatt/use-prefers-color-scheme#209]
Hi,

I'm running into an issue illustrated with the screenshot below when installing this hook in my project. I think it arises from a typo of the peer dependencies in the package.json file. I tried to create a PR but it looks like the repository isn't set up for contributions.

<img width="986" alt="Screen Shot 2022-12-13 at 10 34 54 AM" src="https://user-images.githubusercontent.com/47408981/207376314-36e0e1c4-59c0-4374-a3cd-62a12b7b4150.png">

**Comment by anatoliygatt** [comment]
Hi @kwam1na, thanks for reporting this. The issue has been fixed and released https://www.npmjs.com/package/@anatoliygatt/use-prefers-color-scheme/v/1.0.6.

The repo is open to contributors, so you should be able to create a pull request.
